[package]
name = "randump"
version = "0.1.0"
authors = ["duslabo <duslabo1@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketcan = "1.7.0"
termion = "1.5.5"
argh = "0.1.3"
